api_platform:
    title: Hello API Platform
    # enable_docs: true
    # enable_entrypoint: true
    enable_swagger_ui: true
    version: 1.0.0
    enable_link_security: true
    formats:
        # multipart: ['multipart/form-data']
        # json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        pagination_items_per_page: 10
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    collection:
        pagination:
            page_parameter_name: _page