api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_docs: true
    enable_swagger: true
    enable_swagger_ui: true
    enable_link_security: true
    formats:
        # multipart: ['multipart/form-data']
        # json: ['application/json']
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        pagination_client_enabled: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 100
        pagination_client_items_per_page: true  #allow client to pass dynamic item perpage from (react, veu, etc)
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        middleware: []
    collection:
        order_parameter_name: 'order'
        pagination:
            enabled: true
            page_parameter_name: page
            items_per_page_parameter_name: size