vich_uploader:
    db_driver: orm
    mappings:
        asset_storage:
            uri_prefix: '%env(UPLOAD_URI)%'
            upload_destination: '%kernel.project_dir%/public/%env(UPLOAD_URI)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer