controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_admin_login_check:
    path: /api/login/admin

api_customer_login_check:
    path: /api/login/customer
